### ISSUE TITLE
Use -ldflags "-X main.userAgent=pulumi-confluentcloud/1.6.0 when building pulumi / pulumi-confluentcloud provider

### ISSUE THREAD

**Issue by linouk23** [pulumi/pulumi-confluentcloud#28]
### What
This is a follow up to https://github.com/pulumi/pulumi-confluentcloud/issues/26.

In `1.6.0` version of TF Provider we added a new support `userAgent` [flag](https://github.com/confluentinc/terraform-provider-confluent/blob/master/main.go#L26) so it'd be great if you could use it to set to pass something like `pulumi-confluentcloud/1.6.0` via `-ldflags "-X main.userAgent=pulumi-confluentcloud/1.6.0"` such that the resulting user agent would be something like (basically the value of `main.userAgent` + something that is generated via TF Provider):
```
pulumi-confluentcloud/1.6.0 terraform-provider-confluent/1.6.0 (https://confluent.cloud; support@confluent.io) HashiCorp-terraform-exec/0.16.1
```

### Blockers
https://github.com/pulumi/pulumi-confluentcloud/issues/27

**Comment by viveklak** [comment]
@linouk23 thanks for opening the issue. We will add this to our prioritization queue.

**Comment by viveklak** [comment]
@linouk23 it appears even if we set this the user agent, it would still look something like `pulumi-confluentcloud/v1.x.y Terraform/<tfversion> Terraform-Plugin-SDK/<sdkversion> terraform-provider-confluent/v1.x.y (https://confluent.cloud; support@confluent.io)` due to the way user agent synthesis happens here: https://github.com/confluentinc/terraform-provider-confluent/blob/1424d0461556e6434f2031848b430ccd7239610b/internal/provider/provider.go#L237

We can't override the value of `terraformProviderUserAgent` since its a const with a value set. Is the above acceptable?
