### ISSUE TITLE
Unable to upgrade to 1.x from 0.1.0

### ISSUE THREAD

**Issue by DavidHe1127** [pulumi/pulumi-confluentcloud#57]
### What happened?

`pulumi up` operation with `refresh` flag throws error below and I tried the approach suggested in this [thread](https://github.com/pulumi/pulumi-confluentcloud/pull/14) but unfortunately it didn’t work either as running refresh gave me the same error.

```
panic: interface conversion: interface {} is nil, not string
```

Another method I’ve tired was ran `up` without `refresh` while it didn’t emit the error, it wanted to replace the kafka topic which we cannot do as doing so would cause data loss in our prod environment.

So I am looking for the right way to upgrade the package.

### Steps to reproduce

- Create provider alongside minimal Kafka resources using `0.1.0`
- Upgrade package to `1.x` e.g `1.1.1`
- Run `pulumi up`

### Expected Behavior

`up` should run successfully. If code changes are required as mentioned in that thread, I should run `up` without issues after changes are made.

### Actual Behavior

It throws error and stops the operation.

### Output of `pulumi about`

CLI          
Version      3.31.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME            VERSION
aws             5.6.0
confluentcloud  1.4.0
docker          3.0.0
kubernetes      3.22.1
nodejs          unknown

Host     
OS       debian
Version  11.3
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @DavidHe1127, thanks for the issue! I've taken a look at this (and the linked issues). I tried upgrading from 0.1.0 to 1.1.1 following the instructions in #14 and it seems to have worked. Could you tell me if what I am doing differs from your approach?

1. Create a new pulumi project with the 0.1 version of the provider:
```
$ pulumi new typescript
  <configure new project>
$ npm install @pulumi/confluentcloud@0.1.0
```
2. Add the example from #14 to `index.ts`. I copied this exactly, just changing the names (`stack72-2`).
3. Run `pulumi up`, and see the following 7 resources:
```
 +   pulumi:pulumi:Stack                     cc-test-dev  created (0.65s)
 +   ├─ confluentcloud:index:ServiceAccount  roo-test     created (1s)
 +   ├─ confluentcloud:index:Environment     roo-test     created (1s)
 +   ├─ confluentcloud:index:KafkaCluster    roo-test     created (6s)
 +   ├─ confluentcloud:index:RoleBinding     roo-test     created (41s)
 +   ├─ confluentcloud:index:ApiKey          roo-test     created (123s)
 +   └─ confluentcloud:index:KafkaTopic      roo-test     created (12s)
```
4. Upgrade to v1.1.1 of the provider:
```
$ npm install @pulumi/confluentcloud@1.1.1
```
5. Run `pulumi up` again. This reports no changes: `Resources: 7 unchanged`.
6. Run `pulumi refresh`. This shows the diff from httpEndpoint to restEndpoint, as expected:
```
     pulumi:pulumi:Stack                     cc-test-dev
     ├─ confluentcloud:index:Environment     roo-test
     ├─ confluentcloud:index:RoleBinding     roo-test
 ~   ├─ confluentcloud:index:KafkaCluster    roo-test     update     [diff: +restEndpoint-httpEndpoint~__meta]
 ~   ├─ confluentcloud:index:KafkaTopic      roo-test     update     [diff: +restEndpoint~__meta]
     ├─ confluentcloud:index:ServiceAccount  roo-test
 ~   └─ confluentcloud:index:ApiKey          roo-test     update     [diff: +disableWaitForReady]
```
7. In `index.ts`, we can now swap the `httpEndpoint: cluster.httpEndpoint` in the Kafka topic to `restEndpoint: cluster.restEndpoint`, so our code matches the state.

Hopefully this is an acceptable upgrade path? If your process or your code differs from what I did here, could you share it so we can try and find where the problem is occuring? Thanks!

**Comment by DavidHe1127** [comment]
Thanks for your quick response @roothorp. Did you include `--refresh` flag in your `up` operation? That's what I did which could explain why it didn't happen to you? We are planning to remove `--refresh` flag as it seems it doesn't work as expected sometimes.

**Comment by DavidHe1127** [comment]
Will close this issue now as I've found a fix
